# .nosana-ci.yml
nosana:
  description: Build, Test and Deploy dApps!

global:
  image: node:16
  trigger:
    push:
      branches:
        - main

jobs:
  - name: deploy
    secrets:
      - PRIVATE_KEY
    commands:
      - npx hardhat run scripts/deploy.js --network polygon_mumbai
    resources:
      - name: node_modules
      - name: artifacts
      - name: cache

  - name: test
    environment:
      REPORT_GAS: "true"
    commands:
      - npx hardhat test
    resources:
      - name: node_modules
      - name: artifacts
      - name: cache
